# Generated by Django 4.1.1 on 2022-10-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название автомобиля')),
                ('about', models.TextField(verbose_name='Описание автомобиля')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Изображение автомобиля')),
            ],
        ),
    ]
